# Generated by Django 5.1.1 on 2024-09-15 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('desciption', models.TextField(max_length=255)),
                ('shade', models.TextField(max_length=255)),
                ('size', models.TextField(max_length=255)),
            ],
        ),
    ]
